### ISSUE TITLE
Composit bootloader

### ISSUE THREAD

**Issue by SandeepanSengupta** [mattairtech/SAMD-MSD-Bootloader#4]
Is it possible to make a MSD-CDC composit bootloader ? It will be great for noobs like us. I'm being curious after seeing a few composit bootloader on STM32

**Comment by mattairtech** [comment]
Currently, I have no plans to add CDC or VCP to the MSD bootloader (maybe if there is more interest).

**Comment by awatterott** [comment]
@SandeepanSengupta We have made a MSD+CDC bootloader for SAM D21 devices:
https://github.com/watterott/SAM-BAR
It is based on the SAM-BA/Arduino Zero bootloader and SAMD-MSD bootloader from Justin Mattair.

**Comment by mattairtech** [comment]
Thanks awatterott for adding this. I will link to your GitHub page in the readme.
